import streamlit as st
from groq import Groq
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# Get Groq API key
api_key = os.getenv("GROQ_API_KEY")

# Check API key
if not api_key:
    st.error("GROQ_API_KEY not found. Please add it to your .env file.")
    st.stop()

# Create Groq client
client = Groq(api_key=api_key)

# Page configuration
st.set_page_config(
    page_title="AI Blog Generator",
    page_icon="📝",
    layout="wide"
)

# Main title
st.title("📝 AI Blog Generator")

st.subheader("Generate your blog using AI")

st.write(
    "Enter your blog details in the sidebar and click "
    "**Generate Blog**."
)

# Sidebar
with st.sidebar:

    st.title("⚙️ Blog Settings")

    st.subheader("Enter the details")

    # Blog title
    blog_title = st.text_input(
        "Enter your blog title",
        placeholder="Example: Artificial Intelligence in Education"
    )

    # Keywords
    keyword = st.text_input(
        "Enter your keywords (comma-separated)",
        placeholder="AI, education, technology, students"
    )

    # Number of words
    num_words = st.slider(
        "Select the number of words",
        min_value=100,
        max_value=2000,
        value=500,
        step=50
    )

    # Number of images
    num_images = st.slider(
        "Select the number of images",
        min_value=0,
        max_value=10,
        value=3,
        step=1
    )

    # Generate button
    submit_button = st.button(
        "🚀 Generate Blog",
        use_container_width=True
    )


# Generate blog
if submit_button:

    # Check title
    if not blog_title.strip():

        st.warning("⚠️ Please enter a blog title.")

    else:

        # Show loading message
        with st.spinner("🤖 AI is generating your blog..."):

            # Create prompt
            prompt = f"""
You are a professional blog writer.

Write a high-quality and engaging blog about:

Blog Title:
{blog_title}

Keywords:
{keyword}

Requirements:
- Write approximately {num_words} words.
- Start with an attractive introduction.
- Use proper headings and subheadings.
- Naturally use the provided keywords.
- Make the content informative and easy to understand.
- Use paragraphs and bullet points where appropriate.
- End with a strong conclusion.
- Do not mention that the blog was generated by AI.
"""

            try:

                # Call Groq API
                response = client.chat.completions.create(

                    model="openai/gpt-oss-120b",

                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are an expert professional "
                                "blog writer."
                            )
                        },
                        {
                            "role": "user",
                            "content": prompt
                        }
                    ],

                    temperature=0.7,

                    max_tokens=4000
                )

                # Get generated blog
                blog = response.choices[0].message.content

                # Success message
                st.success("✅ Blog generated successfully!")

                # Display blog
                st.markdown("---")

                st.markdown(
                    f"# {blog_title}"
                )

                st.markdown(blog)

                st.markdown("---")

                # Blog information
                st.subheader("📊 Blog Information")

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric(
                        "Words Requested",
                        num_words
                    )

                with col2:
                    st.metric(
                        "Images Requested",
                        num_images
                    )

                with col3:
                    st.metric(
                        "Keywords",
                        len(
                            [
                                x for x in keyword.split(",")
                                if x.strip()
                            ]
                        )
                    )

                # Download button
                st.download_button(
                    label="⬇️ Download Blog",
                    data=blog,
                    file_name="ai_blog.txt",
                    mime="text/plain"
                )

            except Exception as e:

                st.error(
                    f"❌ Error generating blog: {str(e)}"
                )